config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'signup' => 'user_profiles#new'
  get 'users/new'
  get 'movies/test'
  resources :movies
  # map '/' to be a redirect to '/movies'
  #root :to => redirect('/user_profiles')
  root :to => redirect('static_pages/home')
  resources :users
  resources :user_profiles do
    resources :user_verifications
  end
  resources :requests do
    resources :reviews
  end
  resources :task_applications
  resources :order_generations
  resources :addresses
  #resources :track_request
  resources :update_request_statuses
  get 'order_generation/confirm'

  get 'history_rates' => 'reviews#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.haml
.center.jumbotron
  = image_tag "logo.png"
  %h1 Welcome to Sterna
  %h2
    Join our Global Community!
    %br
    %br
    = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary  text-center"
-#  = link_to "Login", login_path, class: "btn btn-lg btn-primary"
-#  = link_to "Logout", logout_path, method: :delete, class: "btn btn-lg btn-primary"
-#  = link_to "Enter Marketplace", requests_path, class: "btn btn-lg btn-primary"