config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'signup' => 'user_profiles#new'
  get 'users/new'
  get 'movies/test'
  resources :movies
  # map '/' to be a redirect to '/movies'
  #root :to => redirect('/user_profiles')
  root :to => redirect('static_pages/home')
  resources :users
  resources :user_profiles do
    resources :user_verifications
  end
  resources :requests do
    resources :reviews
  end
  resources :task_applications
  resources :order_generations
  resources :addresses
  #resources :track_request
  resources :update_request_statuses
  get 'order_generation/confirm'

  get 'history_rates' => 'reviews#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/controllers/order_generation_controller.rb
class OrderGenerationController < ApplicationController
  before_action :require_login
  def index
    params[:order_id] = 12
    @pending_order_id = params[:order_id]
    @applications = TaskApplication.get_application(params[:order_id])
  end

  def edit

  end

  def new

  end

  def show

  end


  def update
    # requester choose a carrier, update relevant information
    puts params
    application = TaskApplication.find(params[:id])
    application.confirm_order
    
    flash[:success] = "Order #{application.order_id} was successfully generated."
    redirect_to user_profiles_path
  end

  private
  def request_params
    params.require(:request).permit(:id, :carrier_id, :status)
  end
end

app/controllers/order_generations_controller.rb
class OrderGenerationsController < ApplicationController
  before_action :require_login
  def index
    @pending_order_id = params[:order_id]
    @applications = TaskApplication.get_application(params[:order_id])
  end

  def edit

  end

  def new

  end

  def show

  end


  def update
    # requester choose a carrier, update relevant information
    puts params
    application = TaskApplication.find(params[:id]) # :id -> application id
    application.pick_carrier
    
    flash[:success] = "Order #{application.order_id} was successfully generated."
    redirect_to user_profiles_path
  end

  private
  def request_params
    params.require(:request).permit(:id, :carrier_id, :status)
  end
end

app/views/order_generations/index.html.haml
-#  This file is app/views/user_profiles/index.html.haml
%h2 Applications

-# = form_tag user_profiles_path, :method => :get, :id => 'ratings_form' do
-#   = hidden_field_tag "title_sort", true if @title_header
-#   = hidden_field_tag ":release_date_sort", true if @date_header
-#   = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'

%table#order_generation.table.table-striped.col-md-12
  %thead
    %tr
      %th Name
      -#%th{:class => @date_header}= link_to 'Release Date', user_profiles_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th Occupation
  %tbody
    = form_tag order_generation_path(@pending_order_id), :method => :put do
      - @applications.each do |application|
        %tr
          %td= application.name
          %td= application.occupation
          %td= radio_button_tag(:carrier_id, value=application.id)
        -#params[:carrier_id] = order.id
      = submit_tag 'Confirm this carrier'
      -#缩进很重要
-# = link_to 'Confirm this order', order_generation_confirm_path
-#TODO: Change this to go back to previous page

app/views/order_generations/show.html.haml
-#  This file is app/views/user_profiles/index.html.haml
%h2 Applications

-# = form_tag user_profiles_path, :method => :get, :id => 'ratings_form' do
-#   = hidden_field_tag "title_sort", true if @title_header
-#   = hidden_field_tag ":release_date_sort", true if @date_header
-#   = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'

%table#order_generation.table.table-striped.col-md-12
  %thead
    %tr
      %th Name
      -#%th{:class => @date_header}= link_to 'Release Date', user_profiles_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th Occupation
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.name
        %td= order.occupation
        %td= radio_button_tag(:carrier_id, value=order.id)
        -#params[:carrier_id] = order.id

= link_to 'Confirm this order', 'order_generation/confirm'
-#TODO: Change this to go back to previous page