config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'signup' => 'user_profiles#new'
  get 'users/new'
  get 'movies/test'
  resources :movies
  # map '/' to be a redirect to '/movies'
  #root :to => redirect('/user_profiles')
  root :to => redirect('static_pages/home')
  resources :users
  resources :user_profiles do
    resources :user_verifications
  end
  resources :requests do
    resources :reviews
  end
  resources :task_applications
  resources :order_generations
  resources :addresses
  #resources :track_request
  resources :update_request_statuses
  get 'order_generation/confirm'

  get 'history_rates' => 'reviews#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/request.rb
class Request < ActiveRecord::Base
  mount_uploader :img_url, ImageUploader

  def self.get_status(order_id)
    order = Request.find_by(id: order_id)
    return order.status
  end

  def self.update_status(order_id, status)
    order = Request.find_by(id:order_id)
    order.status = status
    order.save
  end

  def self.status_num
    return $status_num
  end

  def self.get_requester_request(requester_id)
    Request.where(requester_id: requester_id).order(:status)
  end

  def self.get_carrier_request(carrier_id)
    Request.where(carrier_id: carrier_id).order(:status)
  end

  def get_source_address
    Address.find(self.source_addr_id)
  end

  def get_dest_address
    Address.find(self.dest_addr_id)
  end

  def self.display_pending_requestes()
    Request.where(status:[$requester_unpaid, $carrier_pending])
  end

  # Ref: https://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/
  scope :filter_by_start_date, -> (start_date) { where('expected_delivery_start <= ?', start_date) }
  scope :filter_by_end_date, -> (end_date) { where('expected_delivery_end >= ?', end_date) }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    before_action :require_login, except: [:show, :index]
    include ApplicationHelper

    def show
      # This will show request details page.
      id = params[:id]
      @request = Request.find(id)
    end
  
    def index
      @requests = Request.display_pending_requestes
      if params[:request_filter].present?
        filter = params[:request_filter]

        @start_date = parse_date_select(filter, "expected_delivery_start")
        @requests = @requests.filter_by_start_date(@start_date) if @start_date
        @end_date = parse_date_select(filter, "expected_delivery_end")
        @requests = @requests.filter_by_end_date(@end_date) if @end_date
      else
        @start_date = Date.today
        @end_date = Date.today
      end
    end
  
    def new
      @request = Request.new
      address_data = Address.where(user_id: logged_id)
      @address = address_data.map { |addr| addr.select_option }
    end
  
    def create
      @request = Request.new(request_params)
      if !request_params[:source_addr_id].present? || !request_params[:dest_addr_id].present?
        flash[:danger] = "Please fill in address!"
        address_data = Address.where(user_id: logged_id)
        @address = address_data.map { |addr| addr.select_option }
        render 'new'
      else
        @request.requester_id = logged_id
        @request.status = 0
        @request.created_at = DateTime.now
        if @request.save
          flash[:success] = "New request successfully posted"
          redirect_to requests_path # should redirect to marketplace
        else
          flash[:danger] = "Invalid form values"
          address_data = Address.where(user_id: logged_id)
          @address = address_data.map { |addr| addr.select_option }
          render 'new'
        end
      end
    end
  
    def edit
      @request = Request.find params[:id]
      address_data = Address.where(user_id: logged_id)
      @address = address_data.map { |addr| addr.select_option }
    end
  
    def update
      @request = Request.find params[:id]
      @request.update_attributes!(request_params)
      flash[:success] = "#{@request.title} was successfully updated."
      redirect_to request_path(@request)
    end
  
    private
    def request_params
        params.require(:request).permit(
            :title, :description, :img_url,
            :value,
            :source_addr_id, :dest_addr_id,
            :expected_delivery_start, :expected_delivery_end,
        )
    end
end
  

app/views/requests/edit.html.haml
-# edit.html.haml using partial

%h2 Edit existing request

= form_tag request_path(@request), :method => :put, :multipart => true do

  = label :request, :img_url, 'Image'
  = file_field :request, 'img_url'

  = label :request, :title, 'Title'
  = text_field :request, 'title'

  = label :request, :description, 'Description'
  = text_field :request, 'description'

  = label :request, :value, 'Value($)'
  = text_field :request, 'value'

  = label :request, :source_addr_id, 'Source address'
  = select :request, :source_addr_id, @address

  = label :request, :dest_addr_id, 'Destination address'
  = select :request, :dest_addr_id, @address

  = label :request, :expected_delivery_start, 'Expected Delivery Start Date'
  = date_select :request, :expected_delivery_start

  = label :request, :expected_delivery_end, 'Expected Delivery End Date'
  = date_select :request, :expected_delivery_end

  = submit_tag 'Update request Info', :class => 'btn btn-primary'

app/views/requests/index.html.haml
-#  This file is app/views/requests/index.html.haml
%h2 All Requests

= form_tag requests_path, :method => :get, :id => 'requests_form' do

  %h4 Filter:
  -# TODO(csw1995): Filtering city (Refactoring using foreign key)
  -# = label :request_filter, :source_city, 'Source City'
  -# = text_field :request_filter, 'source_city'

  -# = label :request_filter, :dest_city, 'Destination City'
  -# = text_field :request_filter, 'dest_city'

  = label :request_filter, :expected_delivery_start, 'Earliest Expected Delivery Start Date'
  = date_select :request_filter, :expected_delivery_start, selected: @start_date

  = label :request_filter, :expected_delivery_end, 'Latest Expected Delivery End Date'
  = date_select :request_filter, :expected_delivery_end, selected: @end_date

  = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'

%table#requests.table.table-striped.col-md-12
  %thead
    %tr
      %th Title
      %th Value($)
      %th Source City
      %th Dest City
      %th Start Date
      %th End Date
      %th More details
  %tbody
    - @requests.each do |request|
      %tr
        %td= request.title
        %td= request.value
        %td= request.get_source_address.city
        %td= request.get_dest_address.city
        %td= request.expected_delivery_start.strftime("%B %d, %Y")
        %td= request.expected_delivery_end.strftime("%B %d, %Y")
        %td= link_to "More details", request_path(request)

= link_to 'I want to post new request', new_request_path

app/views/requests/new.html.haml
%h2 Post New Request

= form_tag requests_path, :multipart => true do

  = label :request, :img_url, 'Image'
  = file_field :request, 'img_url'

  = label :request, :title, 'Title'
  = text_field :request, 'title'

  = label :request, :description, 'Description'
  = text_field :request, 'description'

  = label :request, :value, 'Value($)'
  = text_field :request, 'value'

  = label :request, :source_addr_id, 'Source address'
  = link_to 'Add new address', new_address_path
  = select :request, :source_addr_id, @address

  = label :request, :dest_addr_id, 'Destination address'
  = link_to 'Add new address', new_address_path
  = select :request, :dest_addr_id, @address

  = label :request, :expected_delivery_start, 'Expected Delivery Start Date'
  = date_select :request, :expected_delivery_start

  = label :request, :expected_delivery_end, 'Expected Delivery End Date'
  = date_select :request, :expected_delivery_end

  = submit_tag 'Post Request', :class => 'btn btn-primary'

app/views/requests/show.html.haml
-# in app/views/requests/show.html.haml

%h3 Detailed information for #{@request.title}

%ul#details
  %li
    = image_tag(@request.img_url.url, alt: 'Image', style: 'height:300px;width:auto;') if @request.img_url?
  %li
    title:
    = @request.title
  %li
    Description:
    = @request.description
  %li
    Value($):
    = @request.value
  %li
    Source address:
    = @request.get_source_address.show
  %li
    Destination address:
    = @request.get_dest_address.show
  %li
    Expected Delivery Start Date:
    = @request.expected_delivery_start.strftime("%B %d, %Y")
  %li
    Expected Delivery End Date:
    = @request.expected_delivery_end.strftime("%B %d, %Y")

= link_to 'Edit', edit_request_path(@request)
= link_to 'Back to marketplace', requests_path

= form_tag task_applications_path do
  = hidden_field :request, :id
  = submit_tag 'Apply to be carrier', :class => 'btn btn-primary'