config/routes.rb
Rottenpotatoes::Application.routes.draw do
  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'signup' => 'user_profiles#new'
  get 'users/new'
  get 'movies/test'
  resources :movies
  # map '/' to be a redirect to '/movies'
  #root :to => redirect('/user_profiles')
  root :to => redirect('static_pages/home')
  resources :users
  resources :user_profiles do
    resources :user_verifications
  end
  resources :requests do
    resources :reviews
  end
  resources :task_applications
  resources :order_generations
  resources :addresses
  #resources :track_request
  resources :update_request_statuses
  get 'order_generation/confirm'

  get 'history_rates' => 'reviews#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/user_profile.rb
class User_profile < ActiveRecord::Base
  has_many :user_verifications, foreign_key: 'user_id'
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
                                    format: {with: URI::MailTo::EMAIL_REGEXP},
                                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum:6}, allow_blank: true

  def get_valid_verification
    return self.user_verifications.where('end_date > ?', DateTime.now).first
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  # before_action :require_login, except: [:new, :create]
  before_action :require_login, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def show
    # This will show User Center page.
    id = params[:id] # retrieve user_profile ID from URI route
    @user_profile = User_profile.find(id) # look up user_profile by unique ID
    @requester_requests = Request.get_requester_request(id)
    @carrier_requests = Request.get_carrier_request(id)
    @applications = TaskApplication.where(user_id: @user_profile.id)
    @verification = @user_profile.get_valid_verification
    # will render app/views/user_profiles/show.<extension> by default
  end

  def index
    redirect_to user_profile_path(logged_id)
  end

  def new
    @user_profile = User_profile.new
  end

  def create
    @user_profile = User_profile.new(user_params)
    if @user_profile.save
      flash[:success] = "Welcome to Sterna!"
      log_in @user_profile
      redirect_to user_profile_path(@user_profile)
    else
      render 'new'
    end
  end

  def edit
    @user_profile = User_profile.find params[:id]
  end

  def update
    @user_profile = User_profile.find params[:id]
    if @user_profile.update_attributes(user_params)
      flash[:notice] = "#{@user_profile.name} was successfully updated."
      redirect_to user_profile_path(@user_profile)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user_profile).permit(:name, :email, :occupation, :password, :password_confirmation)
    end

    # Confirms the correct user.
    def correct_user
      @user_profile = User_profile.find(params[:id])
      redirect_to(login_path) unless @user_profile == current_user
    end

end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
  def action_pick_carrier_by_requester(status)
    case status
    when $carrier_pending
      "Pick a carrier"
    else
      ""
    end
  end

  def action_pay_by_requester(status)
    case status
    when $requester_unpaid
      "Pay deposit"
    else
      ""
    end
  end

  def action_confirm_by_requester(status)
    case status
    when $order_arrived
      "Confirm arrival"
    else
      ""
    end
  end

  def action_rate_by_requester(status)
    case status
    when $order_unrated
      "Rate this carrier"
    else
      ""
    end
  end

  def no_actions_by_requester(status)
    case status
    when $carrier_unpaid
      "Waiting for carrier confirmation"
    when $order_finished
      "Finished!"
    else
      ""
    end
  end

  def action_confirm_by_carrier(status)
    case status
    when $carrier_unpaid
      "Confirm and pay deposit"
    else
      ""
    end
  end

  def action_update_by_carrier(status)
    if status >= $order_generated && status < $order_arrived
      "Update status"
    else
      ""
    end
  end
end

app/views/user_profiles/edit.html.erb
<!-- -# edit.html.haml using partial

%h2 Edit Existing user_profile

= form_tag user_profile_path(@user_profile), :method => :put do

  = label :user, :name, 'Name'
  = text_field :user_profile, 'name'

  = label :user, :email, 'Email'
  = text_field :user_profile, 'email'

  = label :user, :occupation, 'Occupation'
  = text_field :user_profile, 'occupation'

  = submit_tag 'Update user_profile Info', :class => 'btn btn-primary' -->

  <% provide(:title, "Edit user") %>
  <h1>Update your profile</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user_profile) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

app/views/user_profiles/index.html.haml
-#  This file is app/views/user_profiles/index.html.haml
%h2 All User_profiles

= form_tag user_profiles_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":release_date_sort", true if @date_header
  = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'

%table#user_profiles.table.table-striped.col-md-12
  %thead
    %tr
      %th{:class => @title_header}= link_to 'User_profile Title', user_profiles_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', user_profiles_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
    - @user_profile.each do |user_profile|
      %tr
        %td= user_profile.name
        %td= user_profile.email
        %td= user_profile.occupation
        %td= link_to "More about #{user_profile.name}", user_profile_path(user_profile)

= link_to 'Add new user_profile', new_user_profile_path

app/views/user_profiles/new.html.erb
  <% provide(:title, 'Sign up') %>
  <h1>Sign up</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for(@user_profile) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control'%>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

app/views/user_profiles/show.html.haml
-# in app/views/user_profiles/show.html.haml

%h3 User Center of #{@user_profile.name}

%ul#details
  %li
    name:
    = @user_profile.name
  %li
    email:
    = @user_profile.email
  %li
    valid verification:
    - if @verification
      = link_to "View Current Verification", user_profile_user_verification_path(@user_profile.id, @verification.id)
    - else
      = link_to "Create New Verification", new_user_profile_user_verification_path(@user_profile.id)

= link_to 'Edit User Profile', edit_user_profile_path(@user_profile)
= link_to 'Manage Addresses', addresses_path

%h4 Current published requests as the requester:

%table#requester_requests.table.table-striped.table-hover.col-md-12
  %thead
    %tr
      %th Title
      %th Status
      %th More Info
      %th Actions
  %tbody
    - @requester_requests.each do |request|
      %tr
        %td= request.title
        %td= status_details(request.status)
        %td= link_to "Detail", request_path(request)
        %td
          - if request.status == $requester_unpaid
            = form_tag update_request_status_path(:id => request.id, :next_status => $carrier_pending) , :method => :put do
              %article
              %script.stripe-button{"data-amount" => "#{request.value*100}", 
              "data-description" => "Pay for this order", 
              "data-key" => "pk_test_Y84rnSDJpoMzeAjls6jybumy00xDY84fDZ", 
              "data-locale" => "auto", 
              src: "https://checkout.stripe.com/checkout.js"}

          = link_to action_pick_carrier_by_requester(request.status), task_applications_path(:order_id => request.id)
          = link_to action_confirm_by_requester(request.status), update_request_status_path(request.id, :next_status => $order_unrated) , :method => :put
          = link_to action_rate_by_requester(request.status), request_reviews_path(request.id)
          = no_actions_by_requester(request.status)



%h4 Current taken requests as the carrier:

%table#carrier_requests.table.table-striped.col-md-12
  %thead
    %tr
      %th Title
      %th Status
      %th More Info
      %th Actions

  %tbody
    - @carrier_requests.each do |request|
      %tr
        %td= request.title
        %td= status_details(request.status)
        %td= link_to "Detail", request_path(request)
        %td
          - if request.status == $carrier_unpaid
            = form_tag update_request_status_path(:id => request.id, :next_status => $order_generated) , :method => :put do
              %article
              %script.stripe-button{"data-amount" => "#{request.value*100}", 
                                    "data-description" => "Pay for this order", 
                                    "data-key" => "pk_test_Y84rnSDJpoMzeAjls6jybumy00xDY84fDZ", 
                                    "data-locale" => "auto", 
                                    src: "https://checkout.stripe.com/checkout.js"}

          = link_to action_update_by_carrier(request.status), update_request_statuses_path(:order_id=>request.id)


%h4 Current pending applications as the carrier:

%table#applications.table.table-striped.col-md-12
  %thead
    %tr
      %th Order_id
      %th Actions

  %tbody
    - @applications.each do |appl|
      %tr
        %td= appl.order_id #__TODO__(csw1995): Use foreign key to get details.
        %td
          = link_to "Cancel Application", task_application_path(appl), :method => :delete

= link_to 'Back to Home page', root_path